
// This file has been generated by the GUI designer. Do not modify.
namespace stdtodo
{
	public partial class TodoItemWidget
	{
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.CheckButton checkbutton3;
		
		private global::Gtk.Label label1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget stdtodo.TodoItemWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "stdtodo.TodoItemWidget";
			// Container child stdtodo.TodoItemWidget.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.checkbutton3 = new global::Gtk.CheckButton ();
			this.checkbutton3.CanFocus = true;
			this.checkbutton3.Name = "checkbutton3";
			this.checkbutton3.Label = "";
			this.checkbutton3.Active = true;
			this.checkbutton3.DrawIndicator = true;
			this.checkbutton3.UseUnderline = true;
			this.hbox1.Add (this.checkbutton3);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.checkbutton3]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Padding = ((uint)(3));
			// Container child hbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this.hbox1.Add (this.label1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label1]));
			w2.Position = 1;
			w2.Padding = ((uint)(3));
			this.Add (this.hbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
